version: "3.7"

services:
  app:
    container_name: 'wanted_server'
    build: .
    ports:
      - "80:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/usr/src/app